#!/usr/bin/env bash

#PBS -l walltime=168:0:0
#PBS -r n

#PBS -W umask=002

umask 002

#-----------------------------------------------------#
#                                                     #
# INITIALIZE VARIABLES                                #
#                                                     #
#-----------------------------------------------------#
if [[ -z $SAMPLE ]]; then echo "ERROR: you must supply SAMPLE variable as -v to qsub"; exit 42; fi
if [[ -z $DIR ]]; then echo "ERROR: you must supply DIR variable as -v to qsub"; exit 42; fi
if [[ -z $THREADS ]]; then echo "ERROR: you must supply THREADS variable as -v to qsub"; exit 42; fi
#if [[ -z $MAX_MEM ]]; then echo "ERROR: you must supply MiAX_MEM variable as -v to qsub"; exit 42; fi
if [[ -z $PIPELINE_HOME ]]; then echo "ERROR: you must supply PIPELINE_HOME variable as -v to qsub"; exit 42; fi
if [[ -z $DONE ]]; then echo "ERROR: you must supply DONE variable as -v to qsub"; exit 42; fi
if [[ -z $SFS ]]; then export SFS=0; fi
if [[ -z $KEEP_INTERMEDIATES ]]; then export KEEP_INTERMEDIATES=0; fi

echo "***************************************"
echo "* pipeline.exome.part_4_1.cleanup.qsub"
echo "***************************************"
echo "* SAMPLE:        $SAMPLE"
echo "* DIR:           $DIR"
echo "* THREADS:       $THREADS"
#echo "* MAX_MEM:       $MAX_MEM"
echo "* PIPELINE_HOME: $PIPELINE_HOME"
#echo "* OUTPUTDIR:     $OUTPUTDIR"
echo "* SFS            $SFS"
echo "* KEEP_INTER     $KEEP_INTERMEDIATES"
echo "* VERBOSE        $VERBOSE"
echo "* DONE:          $DONE"
echo "***************************************"

#-----------------------------------------------------#
#                                                     #
# START PIPELINE                                      #
#                                                     #
#-----------------------------------------------------#
cd $DIR
# INIT PIPELINE VARIABLES
. $PIPELINE_HOME/data/templates/init_pipeline.sh $PIPELINE_HOME
# DEFINING PIPELINE SPECIFIC VARIABLES
# LOAD FUNCTION LIBRARY
. $PIPELINE_HOME/data/templates/function.library
# INIT THE SAMPLE
set_verbose $VERBOSE
sample_init $SAMPLE $DIR

##########################################
## FULL PIPELINE - EXOME
echo "*** STARTING RUN CLEANUP"
##########################################
cd $DIR

## CLEANUP STAGE
if [ $VERBOSE ]; then 
echo "****** CMD: sample_cleanup"; 
fi

#remove unused files
rm -v *.sam
rm -v *.sai
rm -vf *fastq.trimmomaticPE.*paired.gz 
rm -vf *fastq.trimmomaticPE.*paired.gz.*.sai

if [ $? -eq 0 ]; then touch $DONE; if [ $VERBOSE ]; then echo SUCCESS; fi; else exit 42; fi

echo "*** WGS PIPELINE FINISHED SUCCESSFULLY"
