#!/usr/bin/env bash

#PBS -l walltime=168:0:0
#PBS -r n
#PBS -j oe
#PBS -W umask=002

umask 002

#-----------------------------------------------------#
#                                                     #
# INITIALIZE VARIABLES                                #
#                                                     #
#-----------------------------------------------------#
if [[ -z $SAMPLE ]]; then echo "ERROR: you must supply SAMPLE variable as -v to qsub"; exit 42; fi
if [[ -z $DIR ]]; then echo "ERROR: you must supply DIR variable as -v to qsub"; exit 42; fi
if [[ -z $THREADS ]]; then echo "ERROR: you must supply THREADS variable as -v to qsub"; exit 42; fi
#if [[ -z $MAX_MEM ]]; then echo "ERROR: you must supply MiAX_MEM variable as -v to qsub"; exit 42; fi
if [[ -z $PIPELINE_HOME ]]; then echo "ERROR: you must supply PIPELINE_HOME variable as -v to qsub"; exit 42; fi
if [[ -z $DONE ]]; then echo "ERROR: you must supply DONE variable as -v to qsub"; exit 42; fi
if [[ -z $SFS ]]; then export SFS=0; fi
#Also GATK_EXOME_DINDEL_VCFFILE

echo "**************************************"
echo "* pipeline.exome.part_3_2.dindel.qsub"
echo "**************************************"
echo "* SAMPLE:        $SAMPLE"
echo "* VCF FILE:      $GATK_EXOME_DINDEL_VCFFILE"
echo "* DIR:           $DIR"
echo "* THREADS:       $THREADS"
#echo "* MAX_MEM:       $MAX_MEM"
echo "* PIPELINE_HOME: $PIPELINE_HOME"
echo "* SFS            $SFS"
echo "* VERBOSE        $VERBOSE"
echo "* DONE:          $DONE"
echo "**************************************"

#-----------------------------------------------------#
#                                                     #
# START PIPELINE                                      #
#                                                     #
#-----------------------------------------------------#
cd $DIR
# INIT PIPELINE VARIABLES
. $PIPELINE_HOME/data/templates/init_pipeline.sh $PIPELINE_HOME
# DEFINING PIPELINE SPECIFIC VARIABLES
# LOAD FUNCTION LIBRARY
. $PIPELINE_HOME/data/templates/function.library
# INIT THE SAMPLE
set_verbose $VERBOSE
sample_init $SAMPLE $DIR

if [[ -z $VCFFILE ]]; then VCFFILE=$GATK_EXOME_DINDEL_VCFFILE; fi
echo "* VCFFILE:       $VCFFILE"
if [[ -z $BAMFILE ]]; then BAMFILE=$GATK_EXOME_BAMFILE; fi
echo "* BAMFILE:       $BAMFILE"
echo "**************************************"

##########################################
## FULL PIPELINE - EXOME
echo "*** STARTING DINDEL"
##########################################
cd $DIR

#make sure there are no user-specific aliases or variables which will alter default python implementation (this can cause problems with dindel)
unalias python
unset PYTHONPATH

## DINDEL
if [ $VERBOSE ]; then echo "****** CMD: sample_dindel $BAMFILE $VCFFILE"; fi
sample_dindel $BAMFILE $VCFFILE 
if [ $? -eq 0 ]; then touch $DONE; if [ $VERBOSE ]; then echo SUCCESS; fi; else exit 42; fi
