#!/usr/bin/env bash

#PBS -l walltime=168:0:0
#PBS -r n
#PBS -j oe
#PBS -W umask=002

umask 002

#-----------------------------------------------------#
#                                                     #
# INITIALIZE VARIABLES                                #
#                                                     #
#-----------------------------------------------------#
if [[ -z $SAMPLE ]]; then echo "ERROR: you must supply SAMPLE variable as -v to qsub"; exit 42; fi
if [[ -z $DIR ]]; then echo "ERROR: you must supply DIR variable as -v to qsub"; exit 42; fi
if [[ -z $THREADS ]]; then echo "ERROR: you must supply THREADS variable as -v to qsub"; exit 42; fi
#if [[ -z $MAX_MEM ]]; then echo "ERROR: you must supply MiAX_MEM variable as -v to qsub"; exit 42; fi
if [[ -z $PIPELINE_HOME ]]; then echo "ERROR: you must supply PIPELINE_HOME variable as -v to qsub"; exit 42; fi
if [[ -z $CENTER ]]; then echo "ERROR: you must supply CENTER variable as -v to qsub"; exit 42; fi
if [[ -z $DONE ]]; then echo "ERROR: you must supply DONE variable as -v to qsub"; exit 42; fi
if [[ -z $SFS ]]; then export SFS=0; fi
if [[ -z $KEEP_INTERMEDIATES ]]; then export KEEP_INTERMEDIATES=0; fi

echo "********************************************"
echo "* pipeline.exome.part_2_2.MT_Filtering.qsub"
echo "********************************************"
echo "* SAMPLE:                   $SAMPLE"
echo "* DIR:                      $DIR"
echo "* THREADS:                  $THREADS"
#echo "* MAX_MEM:                  $MAX_MEM"
echo "* PIPELINE_HOME:            $PIPELINE_HOME"
echo "* CENTER:                   $CENTER"
echo "* SFS                       $SFS"
echo "* KEEP INTERMEDIATES        $KEEP_INTERMEDIATES"
echo "* VERBOSE                   $VERBOSE"
echo "* DONE:                     $DONE"
echo "********************************************"

#-----------------------------------------------------#
#                                                     #
# START PIPELINE                                      #
#                                                     #
#-----------------------------------------------------#
cd $DIR
# INIT PIPELINE VARIABLES
. $PIPELINE_HOME/data/templates/init_pipeline.sh $PIPELINE_HOME
# DEFINING PIPELINE SPECIFIC VARIABLES
# LOAD FUNCTION LIBRARY
. $PIPELINE_HOME/data/templates/function.library
# INIT THE SAMPLE
set_verbose $VERBOSE
sample_init $SAMPLE $DIR
if [ $FUNCTION_LIBRARY_INIT -ne 1 ]; then echo "INIT SAMPLE PROBLEM"; exit 42; fi

##########################################
## FULL PIPELINE - EXOME
echo "*** STARTING FILTER MT"
##########################################
cd $DIR

## FILTER MT
if [[ $SFS -eq 1 || ! `find ./ -maxdepth 1 -name "$DONE"` ]]; then
  if [ $VERBOSE ]; then echo "****** CMD: sample_filter_MT $GATK_MT_BAMFILE $GATK_BAMFILE_MT_FILTERED"; fi
  sample_filter_MT $GATK_MT_BAMFILE $GATK_BAMFILE_MT_FILTERED
  if [ $? -eq 0 ]; then  
    if [[ $KEEP_INTERMEDIATES -eq 0 ]]; then rm -fv $GATK_MT_BAMFILE ${GATK_MT_PREFIX}.${SAMPLE}.clean.dedup.recal.bai ; fi
    touch $DONE;
    if [ $VERBOSE ]; then echo SUCCESS; fi;  
  else exit 42; fi
else if [ $VERBOSE ]; then echo "****** SKIP sample_filter_MT"; fi
fi
