#!/usr/bin/env bash

#PBS -l walltime=48:0:0
#PBS -r n
#PBS -j oe
#PBS -W umask=002

umask 002

#-----------------------------------------------------#
#                                                     #
# INITIALIZE VARIABLES                                #
#                                                     #
#-----------------------------------------------------#
if [[ -z $SAMPLE ]]; then echo "ERROR: you must supply SAMPLE variable as -v to qsub"; exit 42; fi
if [[ -z $DIR ]]; then echo "ERROR: you must supply DIR variable as -v to qsub"; exit 42; fi
if [[ -z $THREADS ]]; then echo "ERROR: you must supply THREADS variable as -v to qsub"; exit 42; fi
#if [[ -z $MAX_MEM ]]; then echo "ERROR: you must supply MiAX_MEM variable as -v to qsub"; exit 42; fi
if [[ -z $PIPELINE_HOME ]]; then echo "ERROR: you must supply PIPELINE_HOME variable as -v to qsub"; exit 42; fi
if [[ -z $FASTQ1 ]]; then echo "ERROR: you must supply FASTQ1 variable as -v to qsub"; exit 42; fi
if [[ -z $FASTQ2 ]]; then echo "ERROR: you must supply FASTQ2 variable as -v to qsub"; exit 42; fi
if [[ -z $SAM ]]; then echo "ERROR: you must supply SAM variable as -v to qsub"; exit 42; fi
if [[ -z $RUN ]]; then echo "ERROR: you must supply RUN variable as -v to qsub"; exit 42; fi
if [[ -z $GENOME ]]; then echo "ERROR: you must supply GENOME variable as -v to qsub"; exit 42; fi
if [[ -z $CENTER ]]; then echo "ERROR: you must supply CENTER variable as -v to qsub"; exit 42; fi
if [[ -z $DONE ]]; then echo "ERROR: you must supply DONE variable as -v to qsub"; exit 42; fi
if [[ -z $SFS ]]; then export SFS=0; fi
if [[ -z $KEEP_INTERMEDIATES ]]; then export KEEP_INTERMEDIATES=0; fi
if [[ -z $LIB ]]; then export LIB=LIB1; else export LIBRARY; fi

echo "************************************************************"
echo "* pipeline.generic.part_1_4.align_bwa_mem_pe.in_fastq.qsub"
echo "************************************************************"
echo "* SAMPLE:        $SAMPLE"
echo "* DIR:           $DIR"
echo "* THREADS:       $THREADS"
#echo "* MAX_MEM:       $MAX_MEM"
echo "* PIPELINE_HOME: $PIPELINE_HOME"
echo "* FASTQ1:        $FASTQ1"
echo "* FASTQ2:        $FASTQ2"
echo "* SAM:           $SAM"
echo "* RUN:           $RUN"
echo "* LIB:           $LIB"
echo "* GENOME:        $GENOME"
echo "* CENTER:        $CENTER"
echo "* SFS            $SFS"
echo "* KEEP INTER:    $KEEP_INTERMEDIATES"
echo "* VERBOSE        $VERBOSE"
echo "* DONE:          $DONE"
echo "****************************************************"

#-----------------------------------------------------#
#                                                     #
# START PIPELINE                                      #
#                                                     #
#-----------------------------------------------------#
cd $DIR
# INIT PIPELINE VARIABLES
. $PIPELINE_HOME/data/templates/init_pipeline.sh $PIPELINE_HOME
# DEFINING PIPELINE SPECIFIC VARIABLES
# LOAD FUNCTION LIBRARY
. $PIPELINE_HOME/data/templates/function.library
# INIT THE SAMPLE
set_verbose $VERBOSE
sample_init $SAMPLE $DIR
if [ $FUNCTION_LIBRARY_INIT -ne 1 ]; then echo "INIT SAMPLE PROBLEM"; exit 42; fi
if [[ $GENOME == "v37" ]]; then REFERENCE=$REF
elif [[ $GENOME == "MT" ]]; then REFERENCE=$REF_MT
else REFERENCE=$GENOME; CHANGE_REF=1;
fi
#else echo "Unkown GENOME to use in alignment \"$GENOME\""; exit 42; fi

cd $DIR
if [ $VERBOSE ]; then 
  echo "****** CMD: sample_BWA_alignMemPE $FASTQ1 $FASTQ2 $SAM $THREADS $REFERENCE @RG"\\t"ID:${RUN}"\\t"PL:illumina"\\t"PU:${RUN}_PU"\\t"LB:${LIB}"\\t"SM:${SAMPLE}"\\t"CN:${CENTER}"; 
  if [[ $CHANGE_REF -eq 1 ]]; then
    echo "cat $REF_BWA_SQ_HEADER <(grep -vP "^@SQ" $SAM ) > $SAM.tmp && mv $SAM.tmp $SAM; ";
  fi  
fi
sample_BWA_alignMemPE $FASTQ1 $FASTQ2 $SAM $THREADS $REFERENCE @RG"\t"ID:${LIB}-${RUN}"\t"PL:illumina"\t"PU:${RUN}"\t"LB:${LIB}"\t"SM:${SAMPLE}"\t"CN:${CENTER}
if [ $? -eq 0 ]; then 
  if [[ $CHANGE_REF -eq 1 ]]; then
    cat $REF_BWA_SQ_HEADER <(grep -vP "^@SQ" $SAM ) > $SAM.tmp && mv $SAM.tmp $SAM;
    if [ $? -eq 0 ]; then
      touch $DONE;
      if [ $VERBOSE ]; then echo SUCCESS; fi;
    else echo "*** Problem in reheading of sample_BWA_alignMemPE"; exit 42; fi
  else 
    touch $DONE;
    if [ $VERBOSE ]; then echo SUCCESS; fi;
  fi
else echo "*** Problem in sample_BWA_alignMemPE"; exit 42; fi

